version: '3.8'
services:

### Mysql container
  mysql:
    container_name: "MySql_netapi"
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: item
      MYSQL_USER: item_user
      MYSQL_PASSWORD: item_pass
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: