# version: '3.8'
services:
  api:
    container_name: "aspnet_api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=item;User=item_user;Password=item_pass;
    depends_on:
      - mysql

### Mysql container
  mysql:
    container_name: "MySql_netapi"
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: item
      MYSQL_USER: item_user
      MYSQL_PASSWORD: item_pass
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: